### ISSUE TITLE
Question: production readiness and 1.1

### ISSUE THREAD

**Issue by dcoraboeuf** [SonarSource/sonar-classloader#3]
Hi,

The documentation says something about a 1.1 version, but this version is not available on the Maven Central. Any news about this? The 1.0 is from March already.

Another question: how do you consider the readiness of this library for a production environment?

Thanks,
Damien.

**Comment by simonbrandhof** [comment]
Hi Damien, 

Sorry for the very late answer. Version 1.0 is already used for a while by SonarQube, which is production-ready. Current changes in version 1.1 are minor and do not deserve a new release.

Regards
